name: "Run conformance tests"
description: "Composite action that installs the Bats testing framework and runs zarr conformance tests."
inputs:
  zarr-cli:
    description: "Command to expose as the ZARR_CLI environment variable (e.g. 'Rscript main.R')"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install testing framework"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: "Run conformance tests"
      shell: bash
      env:
        ZARR_CLI: ${{ inputs.zarr-cli }}
        ZARR_CONFORMANCE_DATA: ${{ github.action_path }}/data
      run: |
        echo "=== Environment ==="
        echo "ZARR_CLI: $ZARR_CLI"
        echo "ZARR_CONFORMANCE_DATA: $ZARR_CONFORMANCE_DATA"
        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
        echo ""
        
        # Run tests with TAP output to both file and console
        echo "=== Running Tests ==="
        set +e
        bats --tap ${GITHUB_ACTION_PATH}/tests.sh 2>&1 | tee conformance-test-results.tap
        TEST_EXIT_CODE=${PIPESTATUS[0]}
        set -e
        
        echo ""
        echo "=== Summary ==="
        echo "Tests exit code: $TEST_EXIT_CODE"
        
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "❌ Tests failed or encountered errors"
          exit $TEST_EXIT_CODE
        else
          echo "✅ All tests passed"
        fi
        
    - name: "Upload test results"
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: conformance-test-results
        path: conformance-test-results.tap
