---
title: "Zarr features supported by different implementations"
---

```{r}
#| echo: false
read_junit <- function(path) {
  doc <- xml2::read_xml(path)
  successes <- xml2::xml_find_all(doc, ".//testcase[not(failure or error)]")
  failures <- xml2::xml_find_all(doc, ".//testcase[failure or error]")

  data.frame(
    # Can be simplified after https://github.com/r-lib/xml2/issues/433
    feature = c(
      xml2::xml_attr(successes, "name"), 
      xml2::xml_attr(failures, "name")
    ),
    time = c(
      as.numeric(xml2::xml_attr(successes, "time")), 
      as.numeric(xml2::xml_attr(failures, "time"))
    ),
    result = c(
      rep("ok", length(successes)), 
      rep("not ok", length(failures))
    )
  )
}  
```

```{r}
#| echo: false
test_results <- fs::dir_ls("outputs") |> 
  rlang::set_names(~ basename(.x)) |> 
  purrr::imap(function(implementation_path, implementation_name) {
    junit <- read_junit(file.path(implementation_path, "conformance-test-results.xml"))
    metadata <- jsonlite::read_json(
      file.path(implementation_path, "last-run-metadata.json"), 
      simplifyVector = TRUE
    )
    cbind(
      implementation = implementation_name,
      junit,
      url = metadata$url,
      createdAt = metadata$createdAt
    )
  })
merged_results <- dplyr::bind_rows(test_results)
```

```{r}
implementation_metadata <- jsonlite::read_json(
  "implementations.json", 
  simplifyVector = TRUE
) |> 
  dplyr::select(name, repo, language)
```

```{r}
#| echo: false
merged_results |> 
  dplyr::left_join(
    implementation_metadata, 
    by = c("implementation" = "name")
  ) |> 
  dplyr::mutate(
    result_with_time = glue::glue(
      "{result}<br><i><small>({formatC(time, format = 'f', digits = 3)} s)</small></i>"
    ),
    implementation = glue::glue("[{implementation}](https://github.com/{repo})"),
    # To get the correct icon
    language = dplyr::if_else(language == "R", "r-project", language)
  ) |> 
  tidyr::pivot_wider(
    id_cols = c("implementation", "url", "createdAt", "language"),
    names_from = "feature",
    values_from = "result_with_time"
  ) |> 
  dplyr::mutate(
    `last run` = glue::glue("[{format(as.POSIXct(createdAt))}]({url})"),
    .after = 1,
    .keep = "unused"
  ) |> 
  gt::gt() |> 
  gt::tab_header(
    title = "Test Results Across Implementations"
  ) |> 
  gt::fmt_markdown(
    columns = dplyr::everything()
  ) |> 
  gt::fmt_icon(
    columns = "language"
  ) |> 
  gt::data_color(
    columns = -dplyr::any_of(c("implementation", "last run", "language")),
    fn = function(x) {
      dplyr::if_else(grepl("^ok", x), "lightgreen", "salmon")
    }
  )
```